my_string=input()
print(my_string)
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
no_spaces_string=my_string.replace(' ','')
print(no_spaces_string)
print(my_string[0])
print(my_string[-1])